apiVersion: v1
kind: Pod 
metadata:
  name: monitorclient
spec:         
  containers:
  - name: monitorclient-container
    image: "docker.io/hokunpark/iitp:monitorClient60"             
    imagePullPolicy: Always
    resources:
     requests:
       cpu: 500m
     limits:
       cpu: 500m
    volumeMounts:
    - mountPath: "/home/tmp"
      name: vol

  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: pvc

  nodeSelector:
     key: worker1